### ISSUE TITLE
Tutorial-27: send ergs and no tokens

### ISSUE THREAD

**Issue by koukarin** [ladopixel/ErgoTutorials.com#6]
Thanks for sharing this example.

When I run the code, it sends the amount of ergs. But how can I send 0 ergs to the different wallets but  aspecific amount of tokens depending on token_id ?

For example, how could I send 0 ergs to the 3 wallets but 10 Comet to the wallet 1, 5 MiGoreng to the wallet 2 and 20 Comet to the wallet 3.

**Comment by ladopixel** [comment]
Glad you like it!!! 
 
For now the tutorial only works for sending nfts or tokens (1 unit). With the latest ergpy update this no longer works. When it is fixed I will update the tutorial.

**Comment by ladopixel** [comment]
Updated tutorial, now you can send as many tokens as you want per token. 
Remember update: pip install -U ergpy

**Comment by koukarin** [comment]
I've just tried and it's works perfectly.

Thanks for all the work you do for the community !
